### ISSUE TITLE
~/go-i2p and ~/go-i2p/config are not created automatically

### ISSUE THREAD

**Issue by hkh4n** [go-i2p/go-i2p#16]
This is on the noise experimental branch:
```
require (
	github.com/go-i2p/go-i2p v0.0.0-20241023173406-c149eef1deaf
)
```
main:
```
import (
	"github.com/go-i2p/go-i2p/lib/router"
)
func main() {
	r, err := router.CreateRouter()
	if err != nil {
		panic(err)
	}
	r.Start()

	r.Stop()
}

```
Found an error when starting a new router. The cause being that the directories required aren't being created automatically.
```
rayquaza@workstation:/mnt/FIVEHUNDREDSSD/enc/Programming/go/go-i2p_main/bin$ ./go-i2p_main 
DEBU[0000] Logging enabled.                              fields.level=debug
DEBU[0000] Creating router with default configuration   
DEBU[0000] Creating router from configuration            config="&{/home/rayquaza/go-i2p/base /home/rayquaza/go-i2p/config 0x62ba60 0x626a00}"
DEBU[0000] Router created successfully from configuration 
DEBU[0000] Router created successfully with default configuration 
DEBU[0000] Starting router                              
DEBU[0000] Stopping router                              
DEBU[0000] Entering router mainloop                     
INFO[0000] Creating new StdNetDB                         db_path=/home/rayquaza/go-i2p/config/netDb
DEBU[0000] Created StdNetDB                              netdb_path=/home/rayquaza/go-i2p/config/netDb
DEBU[0000] NetDB directory does not exist, creating it  
DEBU[0000] Creating network database directory           path=/home/rayquaza/go-i2p/config/netDb
ERRO[0000] Failed to create root network database directory  error="mkdir /home/rayquaza/go-i2p/config/netDb: no such file or directory"
ERRO[0000] Failed to ensure NetDB                        error="mkdir /home/rayquaza/go-i2p/config/netDb: no such file or directory"
DEBU[0000] Calculating NetDB size                       
DEBU[0000] Recalculating NetDB size                     
DEBU[0000] Recalculating NetDB size                     
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ef14d]

goroutine 7 [running]:
github.com/go-i2p/go-i2p/lib/netdb.(*StdNetDB).RecalculateSize.func1({0xc00001e1e0, 0x22}, {0x0?, 0x0?}, {0x56f7e0, 0xc0000bad80})
	/usr/local/go/bin/pkg/mod/github.com/go-i2p/go-i2p@v0.0.0-20241023173406-c149eef1deaf/lib/netdb/std.go:142 +0x4d
path/filepath.Walk({0xc00001e1e0, 0x22}, 0xc0000d3b38)
	/usr/local/go/bin/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.1.linux-amd64/src/path/filepath/path.go:425 +0x4a
github.com/go-i2p/go-i2p/lib/netdb.(*StdNetDB).RecalculateSize(0xc00007e108)
	/usr/local/go/bin/pkg/mod/github.com/go-i2p/go-i2p@v0.0.0-20241023173406-c149eef1deaf/lib/netdb/std.go:141 +0xae
github.com/go-i2p/go-i2p/lib/netdb.(*StdNetDB).Size(0xc00007e108)
	/usr/local/go/bin/pkg/mod/github.com/go-i2p/go-i2p@v0.0.0-20241023173406-c149eef1deaf/lib/netdb/std.go:99 +0x1b7
github.com/go-i2p/go-i2p/lib/router.(*Router).mainloop(0xc00007e100)
	/usr/local/go/bin/pkg/mod/github.com/go-i2p/go-i2p@v0.0.0-20241023173406-c149eef1deaf/lib/router/router.go:92 +0x1e5
created by github.com/go-i2p/go-i2p/lib/router.(*Router).Start in goroutine 1
	/usr/local/go/bin/pkg/mod/github.com/go-i2p/go-i2p@v0.0.0-20241023173406-c149eef1deaf/lib/router/router.go:78 +0x1d3
```
I also had to manually create ~/go-i2p and ~/go-i2p/config in order for it to work
```
rayquaza@workstation:/mnt/FIVEHUNDREDSSD/enc/Programming/go/go-i2p_main/bin$ mkdir ~/go-i2p/config
rayquaza@workstation:/mnt/FIVEHUNDREDSSD/enc/Programming/go/go-i2p_main/bin$ ./go-i2p_main 
DEBU[0000] Logging enabled.                              fields.level=debug
DEBU[0000] Creating router with default configuration   
DEBU[0000] Creating router from configuration            config="&{/home/rayquaza/go-i2p/base /home/rayquaza/go-i2p/config 0x62ba60 0x626a00}"
DEBU[0000] Router created successfully from configuration 
DEBU[0000] Router created successfully with default configuration 
DEBU[0000] Starting router                              
DEBU[0000] Stopping router                              
DEBU[0000] Entering router mainloop                     
INFO[0000] Creating new StdNetDB                         db_path=/home/rayquaza/go-i2p/config/netDb
DEBU[0000] Created StdNetDB                              netdb_path=/home/rayquaza/go-i2p/config/netDb
DEBU[0000] NetDB directory does not exist, creating it  
DEBU[0000] Creating network database directory           path=/home/rayquaza/go-i2p/config/netDb
DEBU[0000] Calculating NetDB size                       
DEBU[0000] Recalculating NetDB size                     
DEBU[0000] Recalculating NetDB size                     
INFO[0000] Finished recalculating NetDB size             count=0
DEBU[0000] Updated NetDB size cache file                
DEBU[0000] NetDB Size                                    size=0
DEBU[0000] Router ready                                  at="(Router) mainloop"
^C
```

**Comment by hkh4n** [comment]
proposed fix in https://github.com/go-i2p/go-i2p/pull/17
