### ISSUE TITLE
func (router_info RouterInfo) Bytes() is failing with i2p/i2pd generated routerinfos

### ISSUE THREAD

**Issue by hkh4n** [go-i2p/go-i2p#25]
I've branched off into 10k from routerinfo to test out reading router infos generated by java i2p and i2pd. Upon doing this, this code fails with a SIGSEGV originating at `bytes = append(bytes, keys_and_cert.signingPublicKey.Bytes()...)` in keys_and_cert.go:
```go
// Bytes returns the entire keyCertificate in []byte form, trims payload to specified length.
func (keys_and_cert KeysAndCert) Bytes() []byte {
	bytes := keys_and_cert.publicKey.Bytes()
	bytes = append(bytes, keys_and_cert.Padding...)
	bytes = append(bytes, keys_and_cert.signingPublicKey.Bytes()...)
	bytes = append(bytes, keys_and_cert.keyCertificate.Bytes()...)
	log.WithFields(logrus.Fields{
		"bytes_length":         len(bytes),
		"pk_bytes_length":      len(keys_and_cert.publicKey.Bytes()),
		"padding_bytes_length": len(keys_and_cert.Padding),
		"spk_bytes_length":     len(keys_and_cert.signingPublicKey.Bytes()),
		"cert_bytes_length":    len(keys_and_cert.keyCertificate.Bytes()),
	}).Debug("Retrieved bytes from KeysAndCert")
	return bytes
}
```
this is the error:
```
/Users/kyogre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/bin/go tool test2json -t /Users/kyogre/Library/Caches/JetBrains/GoLand2024.2/tmp/GoLand/___Test10K_in_github_com_go_i2p_go_i2p_lib_common_router_info.test -test.v=test2json -test.paniconexit0 -test.run ^\QTest10K\E$
=== RUN   Test10K
--- FAIL: Test10K (2.10s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10038c1c8]

goroutine 35 [running]:
testing.tRunner.func1.2({0x100451ca0, 0x1005ea750})
	/Users/kyogre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/testing/testing.go:1632 +0x1bc
testing.tRunner.func1()
	/Users/kyogre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/testing/testing.go:1635 +0x334
panic({0x100451ca0?, 0x1005ea750?})
	/Users/kyogre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/runtime/panic.go:785 +0x124
github.com/go-i2p/go-i2p/lib/common/keys_and_cert.KeysAndCert.Bytes({0x14000144080, {0x100490290, 0x1006200c0}, {0x14000078100, 0x0, 0x25e}, {0x0, 0x0}})
	/Users/kyogre/Programming/go/go-i2p/lib/common/keys_and_cert/keys_and_cert.go:90 +0xb8
github.com/go-i2p/go-i2p/lib/common/router_info.RouterInfo.Bytes({{{0x14000144080, {0x100490290, 0x1006200c0}, {0x14000078100, 0x0, 0x25e}, {0x0, 0x0}}}, 0x1400000e390, 0x14000134018, ...})
	/Users/kyogre/Programming/go/go-i2p/lib/common/router_info/router_info.go:128 +0xb8
github.com/go-i2p/go-i2p/lib/common/router_info.Test10K(0x1400012a9c0)
	/Users/kyogre/Programming/go/go-i2p/lib/common/router_info/10k_test.go:162 +0x4e8
testing.tRunner(0x1400012a9c0, 0x10048c320)
	/Users/kyogre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/testing/testing.go:1690 +0xe4
created by testing.(*T).Run in goroutine 1
	/Users/kyogre/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-arm64/src/testing/testing.go:1743 +0x314


Process finished with the exit code 1
```
on branch 10k with commit: https://github.com/hkh4n/go-i2p/commit/003d6c9ab87a09e757553793589e989ca48e8a46

**Comment by hkh4n** [comment]
There must have been some conflict between this diff:

Previous:
```go
// Bytes returns the entire keyCertificate in []byte form, trims payload to specified length.
func (keys_and_cert KeysAndCert) Bytes() []byte {
	bytes := keys_and_cert.keyCertificate.Bytes()
	bytes = append(bytes, keys_and_cert.publicKey.Bytes()...)
	bytes = append(bytes, keys_and_cert.Padding...)
	bytes = append(bytes, keys_and_cert.signingPublicKey.Bytes()...)
	log.WithFields(logrus.Fields{
		"bytes_length": len(bytes),
		"pk_bytes_length": len(keys_and_cert.publicKey.Bytes()),
		"padding_bytes_length": len(keys_and_cert.Padding),
		"spk_bytes_length": len(keys_and_cert.signingPublicKey.Bytes()),
		"cert_bytes_length": len(keys_and_cert.keyCertificate.Bytes()),
	}).Debug("Retrieved bytes from KeysAndCert")
	return bytes
}

```

Current:
```go
// Bytes returns the entire keyCertificate in []byte form, trims payload to specified length.
func (keys_and_cert KeysAndCert) Bytes() []byte {
	bytes := keys_and_cert.publicKey.Bytes()
	bytes = append(bytes, keys_and_cert.Padding...)
	bytes = append(bytes, keys_and_cert.signingPublicKey.Bytes()...)
	bytes = append(bytes, keys_and_cert.keyCertificate.Bytes()...)
	log.WithFields(logrus.Fields{
		"bytes_length":         len(bytes),
		"pk_bytes_length":      len(keys_and_cert.publicKey.Bytes()),
		"padding_bytes_length": len(keys_and_cert.Padding),
		"spk_bytes_length":     len(keys_and_cert.signingPublicKey.Bytes()),
		"cert_bytes_length":    len(keys_and_cert.keyCertificate.Bytes()),
	}).Debug("Retrieved bytes from KeysAndCert")
	return bytes
}

```

**Comment by zzzi2p** [comment]
previous is obviously wrong, it outputs the keycertificate first, it should be last, as in current.

**Comment by hkh4n** [comment]
Corrected by @eyedeekay in https://github.com/go-i2p/go-i2p/pull/23/commits/24bc4c3c178ed695bb0e90d28c9f5861616be775
